### ISSUE TITLE
poly_scale 정확한 동작확인

### ISSUE THREAD

**Issue by seungho-hub** [seungho-hub/cbnu-datastructure-hw1#1]
- poly 자체를 scailing하는거? => 그럼 return type은 왜 void가 아님?
- poly는 그대로 두고 poly 를 sacling한 결과를 return하는 거? => 왜 예제는 아님?

**Comment by jinhyung2003** [comment]
poly_t* poly_scale(poly_t* p, double s)
{
	// sacling parameter가 0이라면 연산을 하지않고 다항식을 deallocate하고, empty 다항식을 return한다.
	if (s == 0.0)
	{
		return poly_zero();
	}
	// scaling parameter가 1이라면, 다항식을 그대로 return한다.
	if (s == 1.0)
	{
		return p;
	}

	// 스케일링된 다항식을 저장할 새로운 다항식
	poly_t* scaled_poly = poly_zero();

	// 각 단항식의 계수를 스케일링하고 새로운 다항식에 추가한다.
	for (int i = 0; i < p->n_terms; i++)
	{
		double scaled_coef = p->terms[i].coef * s;
		poly_attach(scaled_poly, scaled_coef, p->terms[i].exp);
	}
	return scaled_poly;
}

예제가 틀려서 코드를 다음과 맞게 수정하였습니다.
